### ISSUE TITLE
As a user I would like to have a Recycle Bin

### ISSUE THREAD

**Issue by case141** [CS2103-AY1819S2-W13-3/main#210]
so that I can restore data that I lost and have a place to handle removing of data appropriately as my research data is important.

Tasks left:

- [x] implement restore
- [x] implement permanent and non-permanent delete
- [x] create recycle bin mode through introducing recycle bin’s parser class
- [x] implement empty and exit bin commands

Comprises of User Stories #141 #49 
Fully implemented by #209
