### ISSUE TITLE
As a user I would like to be able to search for research materials

### ISSUE THREAD

**Issue by ToonDragon** [CS2103-AY1819S2-W13-3/main#3]
So that I can easily retrieve the information using various categories and have it displayed in an indexed fashion with all details displayed.

- [x] search the sources by title (and their combination)
- [x] search the sources by a combination of tags, title, details, sources, and types (CONJUNCTION)
- [ ] search the sources by a combination of tags, title, details, sources, and types (DISJUNCTION)
- [ ] search the sources by a combination of tags, title, details, sources, and types (NEGATION)
- [x] make the search be able to match parts of words
- [x] make the search be able to match closely related words

**Comment by suriruhani** [comment]
not planning to pursue search by other boolean combinations for the upcoming milestone, both because of time constraint and limited added functionality.
